<!--
    This file acts as stub for installing NuGet dependencies for Unity using the .NET CLI.
-->
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
        <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
        <PostProcessDotNetPackagesForUnityAssemblyFile>$(PkgMrWatts_MSBuild_UnityPostProcessor)/lib/netstandard2.1/MSBuildUnityPostProcessor.dll</PostProcessDotNetPackagesForUnityAssemblyFile>
    </PropertyGroup>

    <ItemGroup>
        <!--
            NOTE: You might want to disable Assembly Version Validation in your Unity project to allow loading two
            packages that have a shared dependency, but only differ in minor or patch versions.

            Note that disabling it will also no longer warn you if major versions mismatch!

            The alternative is to have the package use floating versions, but this requires access to the culprit project:

            https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#floating-versions
        -->

        <!-- Unity package dependencies -->
        <ProjectReference Include="../../unity-utility-package/Library/PackageCache/io.mrwatts.fuelinject@*/PackageNuGetDependencies.csproj" />

        <!-- Development dependencies. -->
        <PackageReference Include="MrWatts.MSBuild.UnityPostProcessor" Version="1.2.2" GeneratePathProperty="true" PrivateAssets="all" />
    </ItemGroup>

    <Import Project="../RoslynAnalyzerDependencies.targets" />

    <!-- NOTE: Necessary because a `dotnet restore` will not prune packages you remove automatically. -->
    <Target Name="CleanUpUnityPackageFolder" BeforeTargets="Restore">
        <Message Text="Cleaning up installed packages to start from a clean slate..." Importance="high" />

        <!-- We can't use NuGetPackageRoot here due to it not being available yet before restore, so read the value explicitly. -->
        <XmlPeek XmlInputPath="nuget.config" Query="configuration/config/add[@key='globalPackagesFolder']/@value">
            <Output TaskParameter="Result" ItemName="value" />
        </XmlPeek>

        <RemoveDir Directories="@(value)" />
    </Target>

    <UsingTask TaskName="UnityPostProcessor.PostProcessDotNetPackagesForUnity" AssemblyFile="$(PostProcessDotNetPackagesForUnityAssemblyFile)" />

    <Target Name="PostProcessDotNetPackagesForUnity">
        <Message Text="Running post-processing script for Unity..." Importance="high" />
        <PostProcessDotNetPackagesForUnity ProjectRoot="$(ProjectDir)/../../unity-utility-package" PackageRoot="$(NuGetPackageRoot)" UnityInstallationBasePath="$(UNITY_INSTALLATION_BASE_PATH)" GenerateAssemblyDefinitionsPerPackageVersion="true" />
    </Target>

    <Target Name="InstallCodingConventionsEditorConfig" AfterTargets="PostProcessDotNetPackagesForUnity">
        <Message Text="Setting root .editorconfig in Unity project root to global one in Code Analysis Rulesets..." Importance="high" />
        <Copy SourceFiles="$(PkgMrWatts_CodeAnalysisRulesets)/Editorconfigs/Global.editorconfig" DestinationFiles="$(ProjectDir)/../../.editorconfig" UseSymbolicLinksIfPossible="True" SkipUnchangedFiles="True" />
    </Target>
</Project>